import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedMain {
  final List<MainModel> results;

  AutogeneratedMain({this.results});

  factory AutogeneratedMain.fromJson(Map<String, dynamic> json) {
    List<MainModel> temp;
    if (json['results'] != null) {
      temp = List<MainModel>();
      json['results'].forEach((v) {
        temp.add(MainModel.fromJson(v));
      });
    }
    return AutogeneratedMain(results: temp);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MainModel extends Equatable {
  final int id;
  final String name;

  MainModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory MainModel.fromJson(Map<String, dynamic> json) {
    return MainModel(json['id'], json['name']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
